"""add room type to studio_rooms

Revision ID: 8618cf4d83ea
Revises: 02c205be4a22
Create Date: 2026-02-18 16:07:23.271062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8618cf4d83ea'
down_revision: Union[str, Sequence[str], None] = '02c205be4a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roomtype = sa.Enum('YOGA', 'PILATES', name='roomtype')
    roomtype.create(op.get_bind())
    op.add_column('studio_rooms', sa.Column('room_type', roomtype, nullable=False))

    op.add_column('reservations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_rooms', 'room_type')
    room_type = sa.Enum('YOGA', 'PILATES', name='roomtype')
    room_type.create(op.get_bind())

    op.drop_column('reservations', 'deleted_at')
    # ### end Alembic commands ###
